apiVersion: v1
kind: ConfigMap
metadata:
  name: mecaniqa-config
data:
  MYSQL_DATABASE: mecaniqa
  SPRING_DATASOURCE_URL: "jdbc:mysql://mecaniqa-db:3306/mecaniqa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATA_REDIS_HOST: "mecaniqa-cache"
  SPRING_DATA_REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: mecaniqa-secrets
type: Opaque
stringData:
  MYSQL_USER: mecaniqa_user
  MYSQL_PASSWORD: password321
  MYSQL_ROOT_PASSWORD: dbpassword321
  SPRING_DATASOURCE_USERNAME: mecaniqa_user
  SPRING_DATASOURCE_PASSWORD: password321
